(library
 (name rabbit_proverif_pv_parse)
 (modules
  param
  parsing_helper
  pitparser
  pitptree
  ptree
  pitlexer
  pv_parser
  types)
 (modules_without_implementation
  pitptree
  ptree
  types)
 (flags (:standard -w +a-4-40-42-70-27-38-39-41-45)))

(ocamllex
 (modules pitlexer))

(ocamlyacc
 (modules pitparser))
